version: '2'
services:
  web:
    image: tomcat:latest
    container_name: nfc
    restart: always
    ports:
      - 9191:8080
    volumes:
      - /home/sysadm/nfc/RestTest.war:/usr/local/tomcat/webapps/RestTest.war
    links:
      - db
  db:
    image: mysql:latest
    container_name: nfc_db
    restart: always
    #ports:
      #- 3306:3306
    volumes:
      - /data/nfc:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'authaccess'
      MYSQL_ROOT_PASSWORD: 'test'

